### ISSUE TITLE
Please put the actual license in the LICENSE file

### ISSUE THREAD

**Issue by tarsius** [echosa/phpplus-mode#28]
Please put the actual license (https://www.gnu.org/licenses/gpl.txt) in the `LICENSE` file instead of the permission statement. Additionally you should consider adding the permission statement to *library headers*, at least the one of the "main library" (`php+-mode.el`).

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by echosa** [comment]
I have updated `LICENSE` and `php+-mode.el`. If you see any other similar changes required in this project or any others of mine, please feel free to make the changes and send in a PR. That would make this process go much faster. :-) Let me know if I did something wrong again this time.

**Comment by tarsius** [comment]
Looks good, no pr needed ;-)
Thanks!
